# In netlify.toml
[functions]
  directory = "netlify/functions/"

# ----------------------------------------------------

# In package.json
{
  "name": "fitfusion-app",
  "version": "1.0.0",
  "description": "KI Fitness Coach",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-fetch": "^2.6.7"
  }
}
